services:
  - type: web
    name: healthcare-tracker
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://<host>:<port>/<dbname>?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: <your_db_user>
      - key: SPRING_DATASOURCE_PASSWORD
        value: <your_db_password>
    dockerContext: ./healthcare
    dockerfilePath: ./healthcare/Dockerfile
    buildCommand: mvn clean package